name: Publish to npm (on tag)

on:
  push:
    tags:
      - "v*.*.*" # trigger only on tags like v0.1.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (and npm registry)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Configure npm auth (from secret)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # write auth token to npmrc for this runner
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          # confirm auth (optional)
          npm whoami || true

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # publish (scoped packages must use --access public)
          npm publish --access public
